apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postfacto-v2-redis-pvc
  namespace: postfacto
spec:
  storageClassName: '' # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: postfacto-v2-redis-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postfacto-v2-redis-pv
  namespace: postfacto
  labels:
    usage: postfacto-v2-redis-pv
spec:
  ## We are assuming that the volume has been already
  ## provisioned by Terraform
  storageClassName: ''
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    secretName: postfacto-storage-account
    shareName: postfacto-v2-redis
    readOnly: false
  claimRef:
    name: postfacto-v2-redis-pvc
    namespace: postfacto
