controller:
  nodeSelector:
    kubernetes.azure.com/mode: system
    kubernetes.io/os: linux
  resources:
    requests:
      cpu: 100m
      memory: 180Mi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 50
    behavior:
      scaleDown:
        stabilizationWindowSeconds: 300
        policies:
          - type: Pods
            value: 1
            periodSeconds: 180
      scaleUp:
        stabilizationWindowSeconds: 300
        policies:
          - type: Pods
            value: 1
            periodSeconds: 60
defaultBackend:
  enabled: true
  nodeSelector:
    kubernetes.azure.com/mode: system
    kubernetes.io/os: linux
