image:
  repository: docker.io/postfacto/postfacto
  pullPolicy: IfNotPresent
appVersion: 4.2.0
adminEmail: example@example.com
adminPassword: password
secretKeyBase: 'Wklj85GHJg'
## Postfacto pods should be scheduled onto a node
## with label having key "node.kubernetes.io/workload" and value "applications"
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node.kubernetes.io/workload
              operator: In
              values:
                - applications

## bitnami redis chart values
## ref: https://github.com/bitnami/charts/blob/master/bitnami/redis/README.md
redis:
  storageClass: ''
  usePassword: true
  password: 'redis-password'
  persistence:
    enabled: true
    existingClaim: 'postfacto-v2-redis-data-claim'
  master:
    ## postegresql pods should be scheduled onto a node
    ## with label having key "node.kubernetes.io/workload" and value "databases"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node.kubernetes.io/workload
                  operator: In
                  values:
                    - databases

  slave:
    storageClass: ''
    ## redis pods should be scheduled onto a node
    ## with label having key "node.kubernetes.io/workload" and value "databases"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node.kubernetes.io/workload
                  operator: In
                  values:
                    - databases

## bitnami postgresql chart values
## ref: https://github.com/bitnami/charts/blob/master/bitnami/postgresql/README.md
postgresql:
  postgresqlPassword: 'postgresql-password'
  persistence:
    enabled: true
    existingClaim: 'postfacto-v2-postgresql-data-claim'
  volumePermissions:
    enabled: true
  master:
    ## postegresql pods should be scheduled onto a node
    ## with label having key "node.kubernetes.io/workload" and value "databases"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node.kubernetes.io/workload
                  operator: In
                  values:
                    - databases
  slave:
    ## postegresql pods should be scheduled onto a node
    ## with label having key "node.kubernetes.io/workload" and value "databases"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node.kubernetes.io/workload
                  operator: In
                  values:
                    - databases
